name: Feature Request
description: Suggest an idea for DateUtils
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - KirkBrooks

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Your ideas help make DateUtils better for the 4D community.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case and how this feature would help
      placeholder: In my 4D application, I need to...
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Code
      description: If applicable, provide an example of how you'd like to use this feature
      render: 4d
      placeholder: |
        // Example of how the new feature might work
        $result := DateFormatter.newFeature(Current date; "some-parameter")

  - type: checkboxes
    id: compatibility
    attributes:
      label: Compatibility Considerations
      description: Please consider compatibility aspects
      options:
        - label: This feature should be backward compatible
        - label: This feature may require breaking changes
        - label: This feature is specific to certain 4D versions

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here
